server:
  port: 9192

spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/kiroku_app_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-request-size: 5MB
    max-request-size: 5MB
    file-size-threshould: 2KB
  
